### ISSUE TITLE
Mission Control service Timeout issue

### ISSUE THREAD

**Issue by pmosbach** [nasa/VADER#18]
Log excerpt:

```
10:14:47 T:3972  NOTICE: ----------------------------------------
10:14:47 T:3972  NOTICE: Exception happened during processing of request from
10:14:47 T:3972  NOTICE: ('130.40.XXX.XXX', 57816)
10:14:47 T:3972   ERROR: Traceback (most recent call last):
10:14:47 T:3972   ERROR:   File "C:\Program Files\XBMC\system\python\Lib\SocketServer.py", line 283, in _handle_request_noblock
10:14:47 T:3972   ERROR:     self.process_request(request, client_address)
10:14:47 T:3972   ERROR:   File "C:\Program Files\XBMC\system\python\Lib\SocketServer.py", line 309, in process_request
10:14:47 T:3972   ERROR:     self.finish_request(request, client_address)
10:14:47 T:3972   ERROR:   File "C:\Program Files\XBMC\system\python\Lib\SocketServer.py", line 322, in finish_request
10:14:47 T:3972   ERROR:     self.RequestHandlerClass(request, client_address, self)
10:14:47 T:3972   ERROR:   File "C:\Program Files\XBMC\system\python\Lib\SocketServer.py", line 617, in __init__
10:14:47 T:3972   ERROR:     self.handle()
10:14:47 T:3972   ERROR:   File "C:\Program Files\XBMC\system\python\Lib\BaseHTTPServer.py", line 329, in handle
10:14:47 T:3972   ERROR:     self.handle_one_request()
10:14:47 T:3972   ERROR:   File "C:\Program Files\XBMC\system\python\Lib\BaseHTTPServer.py", line 312, in handle_one_request
10:14:47 T:3972   ERROR:     self.raw_requestline = self.rfile.readline()
10:14:47 T:3972   ERROR:   File "C:\Program Files\XBMC\system\python\Lib\socket.py", line 444, in readline
10:14:47 T:3972   ERROR:     data = self._sock.recv(self._rbufsize)
10:14:47 T:3972   ERROR: timeout: timed out
10:14:47 T:3972  NOTICE: ----------------------------------------
```

**Comment by pmosbach** [comment]
Is this issue caused by thread blocking?

**Comment by pmosbach** [comment]
Adding a threading mixin does not seem to have fixed the issue, but it's possible that removing the channel and program name sections have resolved the problem.
